version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: Asia/Hong_Kong
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    groups:
      production-dependencies:
        dependency-type: production
        patterns:
          - "*"
      development-dependencies:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "02:30"
      timezone: Asia/Hong_Kong
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
